<?php /* Smarty version 2.6.20, created on 2015-06-21 17:45:22
         compiled from header.tpl */

$this->_cache_serials['/home/hoodclips14/public_html/Smarty/templates_c/%%F7^F7F^F7F34188%%header.tpl.inc'] = '30bfde8ea2eb19289651fbfe7c67a60a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'dropdown_menu_video_categories', 'header.tpl', 255, false),array('function', 'dropdown_menu_article_categories', 'header.tpl', 263, false),)), $this); ?>
<?php
function _smarty_tplfunc_30bfde8ea2eb19289651fbfe7c67a60a_0(&$_smarty)
{
echo smarty_art_html_list_categories(array('max_levels' => 3), $_smarty);
}



?>
